# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/oauth/token?grant_type=password&username={{username}}&password={{password}}
Accept: application/json
Authorization: Basic Y29ycDpzZWNyZXQ=

###


POST http://localhost:8080/oauth/token?grant_type=password&username=geoff@matrangola.com&password=password
Accept: application/json
Authorization: Basic Y29ycDpzZWNyZXQ=

###

POST http://localhost:8080/oauth/token?grant_type=password&username=tsmith&password=password
Accept: application/json
Authorization: Basic Y29ycDpzZWNyZXQ=

###

POST http://localhost:8080/oauth/token?grant_type=password&username={{username}}&password={{password}}
Accept: application/json
Authorization: Basic corp secret

###

GET http://localhost:8080/indicators/aboveAvg?code=IP.PAT.RESD&access_token=023bafea-d05a-4a87-89d6-012e7f690de0
Accept: application/json

###

GET http://localhost:8080/indicators/aboveAvg?code=IP.PAT.RESD
Authorization: Bearer 023bafea-d05a-4a87-89d6-012e7f690de8
Accept: application/json

###
